[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  # Avoid false positives: these keys are expected in client bundles
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_URL"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js", "@supabase/ssr"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
